DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS forums CASCADE;
DROP TABLE IF EXISTS threads CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS usersForums CASCADE;

CREATE TABLE IF NOT EXISTS users
(
  id SERIAL NOT NULL PRIMARY KEY,
  email VARCHAR UNIQUE NOT NULL,
  fullname VARCHAR NOT NULL,
  about TEXT,
  nickname VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS forums
(
  id SERIAL NOT NULL PRIMARY KEY ,
  posts BIGINT DEFAULT 0,
  slug TEXT  UNIQUE NOT NULL,
  threads INTEGER DEFAULT 0,
  title VARCHAR NOT NULL,
  userNickname VARCHAR NOT NULL REFERENCES users(nickname)
);

CREATE TABLE IF NOT EXISTS threads
(
  id SERIAL NOT NULL UNIQUE PRIMARY KEY,
  author VARCHAR NOT NULL REFERENCES users(nickname),
  created TIMESTAMP WITH TIME ZONE DEFAULT  current_timestamp,
  forum INTEGER NOT NULL REFERENCES forums(id),
  message TEXT NOT NULL,
  slug TEXT UNIQUE,
  title VARCHAR NOT NULL,
  votes INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS posts
(
  id SERIAL NOT NULL UNIQUE PRIMARY KEY,
  author VARCHAR NOT NULL REFERENCES users(nickname),
  created TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp,
  forum TEXT,
  isEdited BOOLEAN NOT NULL DEFAULT FALSE,
  message TEXT NOT NULL,
  parent BIGINT DEFAULT 0,
  thread INTEGER NOT NULL REFERENCES threads(id)
);

CREATE TABLE IF NOT EXISTS votes
(
  id SERIAL  NOT NULL PRIMARY KEY,
  voterNickname VARCHAR NOT NULL REFERENCES users(nickname),
  voice INTEGER DEFAULT 0,
  voiceThread INTEGER NOT NULL REFERENCES threads(id),
  UNIQUE(voterNickname, voiceThread)
);

CREATE TABLE IF NOT EXISTS usersForums
(
  nickname VARCHAR NOT NULL REFERENCES users(nickname),
  forum INTEGER REFERENCES forums(id)
);

